/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/ryo-watanabe/k8s-snap/pkg/apis/clustersnapshot/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRestorePreferences implements RestorePreferenceInterface
type FakeRestorePreferences struct {
	Fake *FakeClustersnapshotV1alpha1
	ns   string
}

var restorepreferencesResource = schema.GroupVersionResource{Group: "clustersnapshot.rywt.io", Version: "v1alpha1", Resource: "restorepreferences"}

var restorepreferencesKind = schema.GroupVersionKind{Group: "clustersnapshot.rywt.io", Version: "v1alpha1", Kind: "RestorePreference"}

// Get takes name of the restorePreference, and returns the corresponding restorePreference object, and an error if there is any.
func (c *FakeRestorePreferences) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RestorePreference, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(restorepreferencesResource, c.ns, name), &v1alpha1.RestorePreference{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RestorePreference), err
}

// List takes label and field selectors, and returns the list of RestorePreferences that match those selectors.
func (c *FakeRestorePreferences) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RestorePreferenceList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(restorepreferencesResource, restorepreferencesKind, c.ns, opts), &v1alpha1.RestorePreferenceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RestorePreferenceList{ListMeta: obj.(*v1alpha1.RestorePreferenceList).ListMeta}
	for _, item := range obj.(*v1alpha1.RestorePreferenceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested restorePreferences.
func (c *FakeRestorePreferences) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(restorepreferencesResource, c.ns, opts))

}

// Create takes the representation of a restorePreference and creates it.  Returns the server's representation of the restorePreference, and an error, if there is any.
func (c *FakeRestorePreferences) Create(ctx context.Context, restorePreference *v1alpha1.RestorePreference, opts v1.CreateOptions) (result *v1alpha1.RestorePreference, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(restorepreferencesResource, c.ns, restorePreference), &v1alpha1.RestorePreference{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RestorePreference), err
}

// Update takes the representation of a restorePreference and updates it. Returns the server's representation of the restorePreference, and an error, if there is any.
func (c *FakeRestorePreferences) Update(ctx context.Context, restorePreference *v1alpha1.RestorePreference, opts v1.UpdateOptions) (result *v1alpha1.RestorePreference, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(restorepreferencesResource, c.ns, restorePreference), &v1alpha1.RestorePreference{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RestorePreference), err
}

// Delete takes name of the restorePreference and deletes it. Returns an error if one occurs.
func (c *FakeRestorePreferences) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(restorepreferencesResource, c.ns, name), &v1alpha1.RestorePreference{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRestorePreferences) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(restorepreferencesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.RestorePreferenceList{})
	return err
}

// Patch applies the patch and returns the patched restorePreference.
func (c *FakeRestorePreferences) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RestorePreference, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(restorepreferencesResource, c.ns, name, pt, data, subresources...), &v1alpha1.RestorePreference{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RestorePreference), err
}
