/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/ryo-watanabe/k8s-backup/pkg/apis/clusterbackup/v1alpha1"
	scheme "github.com/ryo-watanabe/k8s-backup/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RestorePreferencesGetter has a method to return a RestorePreferenceInterface.
// A group's client should implement this interface.
type RestorePreferencesGetter interface {
	RestorePreferences(namespace string) RestorePreferenceInterface
}

// RestorePreferenceInterface has methods to work with RestorePreference resources.
type RestorePreferenceInterface interface {
	Create(*v1alpha1.RestorePreference) (*v1alpha1.RestorePreference, error)
	Update(*v1alpha1.RestorePreference) (*v1alpha1.RestorePreference, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.RestorePreference, error)
	List(opts v1.ListOptions) (*v1alpha1.RestorePreferenceList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.RestorePreference, err error)
	RestorePreferenceExpansion
}

// restorePreferences implements RestorePreferenceInterface
type restorePreferences struct {
	client rest.Interface
	ns     string
}

// newRestorePreferences returns a RestorePreferences
func newRestorePreferences(c *ClusterbackupV1alpha1Client, namespace string) *restorePreferences {
	return &restorePreferences{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the restorePreference, and returns the corresponding restorePreference object, and an error if there is any.
func (c *restorePreferences) Get(name string, options v1.GetOptions) (result *v1alpha1.RestorePreference, err error) {
	result = &v1alpha1.RestorePreference{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("restorepreferences").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RestorePreferences that match those selectors.
func (c *restorePreferences) List(opts v1.ListOptions) (result *v1alpha1.RestorePreferenceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.RestorePreferenceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("restorepreferences").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested restorePreferences.
func (c *restorePreferences) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("restorepreferences").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a restorePreference and creates it.  Returns the server's representation of the restorePreference, and an error, if there is any.
func (c *restorePreferences) Create(restorePreference *v1alpha1.RestorePreference) (result *v1alpha1.RestorePreference, err error) {
	result = &v1alpha1.RestorePreference{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("restorepreferences").
		Body(restorePreference).
		Do().
		Into(result)
	return
}

// Update takes the representation of a restorePreference and updates it. Returns the server's representation of the restorePreference, and an error, if there is any.
func (c *restorePreferences) Update(restorePreference *v1alpha1.RestorePreference) (result *v1alpha1.RestorePreference, err error) {
	result = &v1alpha1.RestorePreference{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("restorepreferences").
		Name(restorePreference.Name).
		Body(restorePreference).
		Do().
		Into(result)
	return
}

// Delete takes name of the restorePreference and deletes it. Returns an error if one occurs.
func (c *restorePreferences) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("restorepreferences").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *restorePreferences) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("restorepreferences").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched restorePreference.
func (c *restorePreferences) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.RestorePreference, err error) {
	result = &v1alpha1.RestorePreference{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("restorepreferences").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
